import Head from 'next/head'
import { ThemeProvider, Global } from '@emotion/react'
import type { NextPage } from 'next'

import { Header, Landing } from 'layouts'

import ApiProvider from 'lib/ApiContext'

import GlobalStyles from 'styles/global'
import { baseTheme } from 'styles/theme'

import { ICity, IExchange } from 'models'

interface IHome {
  cities: ICity[]
  exchange: IExchange
}

const Home: NextPage<IHome> = (props) => (
  <ThemeProvider theme={baseTheme}>
    <Global styles={GlobalStyles} />

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <ApiProvider value={{ cities: props.cities, exchange: props.exchange }}>
        <Landing />
      </ApiProvider>
    </div>
  </ThemeProvider>
)

export const getStaticProps = async () => {
  const citiesResponse = await fetch(`${process.env.SERVER_URL}/api/cities`, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' }
  })

  const exchangeResponse = await fetch(`${process.env.SERVER_URL}/api/exchange`, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' }
  })

  const cities = await citiesResponse.json()
  const exchange = await exchangeResponse.json()

  return {
    props: { cities, exchange }
  }
}

export default Home
