import Head from 'next/head'
import { ThemeProvider, Global } from '@emotion/react'
import type { NextPage } from 'next'

import { Header, Landing } from 'layouts'

import { ApiProvider, useApi } from 'lib/ApiContext'

import GlobalStyles from 'styles/global'
import { baseTheme } from 'styles/theme'

import { ICity, IExchange } from 'models'

export interface IHome {
  cities: ICity[]
  exchange: IExchange
}

const Home: NextPage<IHome> = () => (
  <ThemeProvider theme={baseTheme}>
    <Global styles={GlobalStyles} />

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Landing />
    </div>
  </ThemeProvider>
)

export default Home
