import Head from 'next/head'
import { ThemeProvider, Global } from '@emotion/react'
import type { NextPage } from 'next'

import ApiProvider from 'lib/ApiContext'
import { useParamsStore } from 'lib/RootStoreContext'

import { IHome } from 'pages'
import { Header } from 'layouts'
import { Params } from 'components'

import GlobalStyles from 'styles/global'
import { baseTheme } from 'styles/theme'

const Select: NextPage<IHome> = (props) => {
  const paramsStore = useParamsStore()

  return (
    <ThemeProvider theme={baseTheme}>
      <Global styles={GlobalStyles} />

      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <ApiProvider value={{ cities: props.cities, exchange: props.exchange }}>
          <Header params={paramsStore.isSet() && <Params variant="editable" />} />
        </ApiProvider>
      </div>
    </ThemeProvider>
  )
}

export const getStaticProps = async () => {
  const citiesResponse = await fetch(`${process.env.SERVER_URL}/api/cities`, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' }
  })

  const exchangeResponse = await fetch(`${process.env.SERVER_URL}/api/exchange`, {
    method: 'GET',
    headers: { 'Content-Type': 'application/json' }
  })

  const cities = await citiesResponse.json()
  const exchange = await exchangeResponse.json()

  return {
    props: { cities, exchange }
  }
}

export default Select

